### ISSUE TITLE
buildpack

### ISSUE THREAD

**Issue by nittygritty94** [Rahien/aoe2-profile#1]
Hello,what is this the build pack for heroku? 
https://github.com/mars/create-react-app-buildpack.git not working.

Plase help , i ll use this.

**Comment by Rahien** [comment]
Hi, sorry for taking so long to get back to you.

I use a Node app to host the frontend, so slightly different from the approach you posted here. I did something along the lines of this: https://devcenter.heroku.com/articles/getting-started-with-nodejs

Good luck!
